#!/usr/bin/env bash

set -e

currentVersion=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version|grep "^[0-9]*\.[0-9]*\.[0-9]*"`
cleanedVersion=`echo $currentVersion | sed -e 's/[^0-9][^0-9]*$//'`
echo $cleanedVersion
